#spring.boot.admin.url: http://localhost:8080/admin
#spring.boot.admin.context-path: /admin
#management.security.enabled: false
#management.context-path: /actuator
#spring:
#  boot:
#    admin:
#      client:
#        management-url: http://localhost:8080/actuator
#
#
server:
  port: 8805

spring:
  application:
    name: spring-actuator-test
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  #        include: 'prometheus,health,metrics,httptrace,liquibase,flyway,env,loggers,mappings,autoconfig,beans,configprops,dump,info,httptrace,sentinel'
  metrics:
#    tags:
#      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
    export:
      prometheus:
        pushgateway:
          enabled: true
          base-url: http://11.164.62.162:9091 #部署地址
          push-rate: 10s  #推送频率
  info:
    defaults:
      enabled: true

  endpoint:
    health:
      show-details: always
  server:
    port: 8806